CRS/config/routes.rb
Rails.application.routes.draw do
  resources :post_attachments
  devise_for :users, controllers: { registrations: 'users/registrations'}
  resources :rent_posts
  root to: 'rent_posts#index'
  
  resources :users, only: [:show] do 
    post 'follow', to: 'users#follow', as: :follow, on: :member
  end
  
  #유저 페이지 user page
  get 'users/:id', to: 'users#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #렌트댓글 Rent_Comment
    #Create
    post '/rent_comments' => 'rent_comments#create'
    #destroy
    delete '/rent_comments/:id' => 'rent_comments#destroy' 

end 

CRS/app/models/user.rb
class User < ApplicationRecord
  rolify
  has_many :rent_posts
  has_many :rent_comments
  
  has_many :followee_follows, foreign_key: :follower_id, class_name: "Follow"
  has_many :followees, through: :followee_follows, source: :followee
  
  has_many :follower_follows, foreign_key: :followee_id, class_name: "Follow"
  has_many :followers, through: :follower_follows, source: :follower
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  after_create :assign_default_role
         
  def assign_default_role
    add_role(:CRSmember)
  end
  
  def toggle_follow(user)
    if self.followers.include?(user)
      self.followers.delete(user)
    else
      self.followers.push(user)
    end
  end
end

CRS/app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

CRS/app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

CRS/app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

CRS/app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:email])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

CRS/app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

CRS/app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

CRS/app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user
    load_and_authorize_resource
    # GET 'users/:id'
    def show
        @rent_posts = @user.rent_posts.order("created_at DESC").page(params[:page]).per(5)
    end
    
    #POST 'users/:id/follow'
    def follow
        @user.toggle_follow(current_user)
        redirect_back(fallback_location: root_path)
    end

    private
  
    def set_user
      @user = User.find(params[:id])
    end
end

CRS/app/helpers/users_helper.rb
module UsersHelper
end

CRS/app/views/users/show.html.erb
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">


<script language="javascript" type='text/javascript'>
  function centerModal() {
    $(this).css('display', 'block');
    var $dialog = $(this).find(".modal-dialog");
    var offset = ($(window).height() - $dialog.height()) / 2;
    // Center modal vertically in window
    $dialog.css("margin-top", offset);
}

$('.modal').on('show.bs.modal', centerModal);
$(window).on("resize", function () {
    $('.modal:visible').each(centerModal);
});
</script>



<div class="container">

<div class="container">

<p id="notice"><%= notice %></p>

  <h1><%= @user.email %>의 게시물</h1>
<% if can? :follow, @user %>
  <%= link_to 'Follow', follow_user_path(@user), method: :post, :class => "btn btn-primary" %>
<% end %>
<h4>
Followees: <button type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal1">
              <%= @user.followees.count %>
           </button>
Followers: <button type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal2">
              <%= @user.followers.count %>
           </button>
</h4>
<br>

	<div class="row">
	
	  <div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
            <h4 class="modal-title" id="myModalLabel">Followees</h4>
          </div>
          <div class="modal-body">
            <ul>
              <% @user.followees.each do |followee| %>
                <li><%= link_to followee.email, "/users/#{followee.id}" %></li>
              <% end %>              
            </ul> 
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>  
    </div>
    
    <div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
            <h4 class="modal-title" id="myModalLabel">Followers</h4>
          </div>
          <div class="modal-body">
            <ul>
              <% @user.followers.each do |follower| %>
                <li><%= link_to follower.email, "/users/#{follower.id}" %></li>
              <% end %>              
            </ul>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>  
    </div>
    
		<div class="table-responsive">
      <table id="main-table" class="table exotic-table">
        <thead>
          <tr class = "text-center">
            <th>랜즈 이름</th>
            <th>지역</th>
            <th>가격</th>
            <th>Rented</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody class="text-center">
          <% @rent_posts.each do |rent_post| %>
            <tr>

              <td><%= rent_post.lens_name %></td>
              <td><%= rent_post.location %></td>
              <td><%= rent_post.price %></td>
              <% if rent_post.rented == true %>
                <td><span class="glyphicon glyphicon-ok green"></td>
              <% else %>
                <td><span class="glyphicon glyphicon-remove red"></td>
              <% end %>
              <td><%= link_to '', rent_post, :class => "glyphicon glyphicon-eye-open"  %></td>
              
              <% if rent_post.user == current_user %>
                <td><%= link_to '', edit_rent_post_path(rent_post), :class => "glyphicon glyphicon-pencil" %></td>
                <td><%= link_to '', rent_post, method: :delete, data: { confirm: ' 게시물을 삭제하시겠습니까??' }, :class => "glyphicon glyphicon-trash" %></td>
              <% else %>
                <td></td>
                <td></td>
              <% end %>
              </tr>
              <% end %>
            </tbody>
      </table>
    </div>
  </div>
<div class="container">
<% if can? :update, @user %>
    <%= link_to 'Edit User', edit_user_registration_path, :class => "btn btn-success" %>
<% end %>
</div>
</div>

<div align="center">
  <%= paginate @rent_posts %>
</div>