CRS/config/routes.rb
Rails.application.routes.draw do
  resources :post_attachments
  devise_for :users, controllers: { registrations: 'users/registrations'}
  resources :rent_posts
  root to: 'rent_posts#index'
  
  resources :users, only: [:show] do 
    post 'follow', to: 'users#follow', as: :follow, on: :member
  end
  
  #유저 페이지 user page
  get 'users/:id', to: 'users#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #렌트댓글 Rent_Comment
    #Create
    post '/rent_comments' => 'rent_comments#create'
    #destroy
    delete '/rent_comments/:id' => 'rent_comments#destroy' 

end 

CRS/app/models/rent_post.rb
class RentPost < ApplicationRecord
    resourcify
    belongs_to :user
    has_many :rent_comments
    has_many :post_attachments
    accepts_nested_attributes_for :post_attachments
    validates :user, presence: true
    
    # mount_uploader :image, LensUploader
 
    # 이미지를 가진 게시글 삭제 시 AWS S3서버에도 자동 삭제처리
    before_destroy :destroy_assets
 
    def destroy_assets
        self.image.remove! if self.image
        self.save!
    end

        
end

CRS/app/controllers/rent_posts_controller.rb
class RentPostsController < ApplicationController
  before_action :authenticate_user! 
  before_action :set_rent_post, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /rent_posts
  # GET /rent_posts.json
  
  def index
    if params.has_key?(:content)
      @rent_posts = RentPost.order("created_at DESC").page(params[:page]).per(5).where('content like ?', "%#{params[:content]}%")
    else
      @rent_posts = RentPost.where(rented: false).order("created_at DESC").page(params[:page]).per(5)
    end
  end

  # GET /rent_posts/1
  # GET /rent_posts/1.json
  def show
    @post_attachment = PostAttachment.where(rent_post: @rent_post.id)
    @token = form_authenticity_token
    @current_user = current_user
  end

  # GET /rent_posts/new
  def new
    @rent_post = RentPost.new
    @post_attachment = @rent_post.post_attachments.build
  end

  # GET /rent_posts/1/edit
  def edit
  end

  # POST /rent_posts
  # POST /rent_posts.json
  def create
    @rent_post = RentPost.new(rent_post_params)
    # @post_attachment = @rent_post.post_attachments.build

    respond_to do |format|
      if @rent_post.save
        if params[:post_attachments]!=nil
          params[:post_attachments]['image'].each do |a|
            @post_attachment = @rent_post.post_attachments.create!(:image => a, :rent_post_id => @rent_post.id)
          end
        else
          @post_attachment = @rent_post.post_attachments.create!(:image => nil, :rent_post_id => @rent_post.id)
        end
        format.html { redirect_to @rent_post, notice: 'Rent post was successfully created.' }
        format.json { render :show, status: :created, location: @rent_post }
      else
        format.html { render :new }
        format.json { render json: @rent_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rent_posts/1
  # PATCH/PUT /rent_posts/1.json
  def update
    @post_attachment = PostAttachment.where(rent_post: @rent_post.id)
    
    respond_to do |format|
      if @rent_post.update(rent_post_params)
        if params[:post_attachments]!=nil
          @post_attachment.destroy_all
          params[:post_attachments]['image'].each do |a|
            @post_attachment = @rent_post.post_attachments.create!(:image => a, :rent_post_id => @rent_post.id)
          end
        end
        format.html { redirect_to @rent_post, notice: 'Rent post was successfully updated.' }
        format.json { render :show, status: :ok, location: @rent_post }
      else
        format.html { render :edit }
        format.json { render json: @rent_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rent_posts/1
  # DELETE /rent_posts/1.json
  def destroy
    check_user
    @rent_post.destroy
    @post_attachment = PostAttachment.where(rent_post: @rent_post.id)
    @post_attachment.destroy_all
    respond_to do |format|
      format.html { redirect_to rent_posts_url, notice: 'Rent post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def mypage
    @rent_posts = current_user.rent_posts
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rent_post
      @rent_post = RentPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rent_post_params
      params.require(:rent_post).permit(:lens_name, :mount, :zoom_lens, :distance, :aperture, :is, :location, :price, :rented, :content, :user_id, post_attachments_attributes: 
  [:id, :rent_post_id, :image])
    end
    
    def check_user
      if @rent_post.user != current_user
        redirect_to root_url
      end
    end 
end

CRS/app/helpers/rent_posts_helper.rb
module RentPostsHelper
end

CRS/app/views/rent_posts/_form.html.erb
<link href="https://netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>

   
<%= form_with(model: rent_post, local: true, multipart: true) do |form| %>
  <div class="container" >
    <% if rent_post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(rent_post.errors.count, "error") %> prohibited this rent_post from being saved:</h2>
  
        <ul>
        <% rent_post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="field">
      <%= form.hidden_field :user_id, value: current_user.id %>
    </div>
  
    <div class="field">  
      <div class="required-field-block">
        <%= form.label :lens_name %>
        <%= form.text_field :lens_name, :class => 'form-control', style: "width: 250px; margin: 0" %>
        <br>
      </div>
    </div>  
  
    <%#= form.fields_for :post_attachments do |p| %>
      <div class="field">
        <%= form.label :image %>
        <img id="img_prev" src="<%= @rent_post.image %>" > <!--대표이미지 프리뷰 -->
        <%= form.file_field :image, accept: 'image/png, image/gif, image/jpg', :multiple => true, :onchange => "readURL(this);", name: "post_attachments[image][]"%>
      </div>
    <%# end %>
    
    <div class="field">
      <div class="required-field-block">
        <br>
        <%= form.label :mount %>
        <%= form.text_field :mount, :class => 'form-control', style: "width: 250px; margin: 0 "%>
      </div>
    </div>  
  
    <div class="field">
      <div class="required-field-block">
        <br>          
        <%= form.label :zoom_lens %>
        <%= form.text_field :zoom_lens, :class => 'form-control', style: "width: 250px; margin: 0 "%>
      </div>
    </div>  
    
    <div class="field">
      <br>          
      <%= form.label :distance %>
      <p>
      <%= form.number_field :distance %>
      mm
      </p>
    </div>
  
  
    <div class="field">
      <br>          
      <%= form.label :aperture %>
      <p>
        f/
      <%= form.number_field :aperture %>
      </p>
      <br>
    </div>
    
   
    
    <div class="field">
      <div class="required-field-block">
        <%= form.label :location %>
        <%= form.text_field :location, :class => 'form-control', style: "width: 250px; margin: 0 "%>
      </div>
    </div>  
  
    <div class="field">
      <br>          
      <%= form.label :price %>
      <p>
      <%= form.number_field :price %>
      원
      </p>
    </div>
  
    <div class="field">
      <br>
      <%= form.label :is %>
      <a>
      <%= form.check_box :is %>&nbsp
      <b>I have it !</b>
      </a>
      <br>
    </div>  
    
    <div class="field">
      <br>
      <%= form.label :rented %>
      <a>
      <%= form.check_box :rented %> &nbsp
      <b>Rented !</b>
      </a>
    </div>
    
    <div class="field">
      <%= form.label :content %>
      <div class="container">
      	<div class="row">
          <%= form.text_area :content %>
        </div>
      </div>
    </div>
    
    <div class="row">
      <div class="actions">&nbsp&nbsp
        <%= form.submit class: "btn btn-labeled btn-success" %> 
      </div>
    </div>  
  </div>  
<% end %>

CRS/app/views/rent_posts/edit.html.erb
<form style= "font-family: 'Comic Sans MS', cursive, sans-serif; font-size: 300%" class= "container";>
    Editing Rent Post 
</form>
<%= render 'form', rent_post: @rent_post %>

<%= link_to '뒤로가기', rent_posts_path %>

CRS/app/views/rent_posts/index.html.erb
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

<p>
<div class="container">
  <p id="notice"><%= notice %></p>
  <form style= "font-family: 'Comic Sans MS', cursive, sans-serif; font-size: 300%">
    Rent Posts
  </form>
	<div class="row" align = "right">
	  <%= link_to '새로운 글 작성', new_rent_post_path, :class => "btn btn-default" %>
	  <div class="search">
      <%= form_tag rent_posts_path, method: :get do %>
        <%= text_field_tag :content, params[:content], :class => "form-control input-sm", style: "maxlength=64px;" %>
        <button type="submit" class="btn btn-primary btn-sm" style="position:absolute; height: 30px; right: 0;top: 5px; border-radius:1px;">검색</button>
      <% end %> 
  </div>

<br>

	<div class="row">
    </div>
    
		<div class="table-responsive">
      <table id="main-table" class="table exotic-table">
        

        <thead>
          <tr class = "text-center">
            <th>작성자</th>
            <th>랜즈이름</th>
            <th>랜즈사진</th>
            <th>지역</th>
            <th>가격</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody class="text-center">
          <% @rent_posts.each do |rent_post| %>
              <tr>
                <td><%= link_to rent_post.user.email, rent_post.user %></td>
                <td><%= rent_post.lens_name %></td>
                <% if PostAttachment.where(rent_post: rent_post.id)[0].image.length == 0 %>
                  <td><img src="https://3.bp.blogspot.com/-ZKBbW7TmQD4/U6P_DTbE2MI/AAAAAAAADjg/wdhBRyLv5e8/s1600/noimg.gif"></td>
                <% else %>
                  <td><img src="<%= PostAttachment.where(rent_post: rent_post.id)[0].image %>", width = 300, height = 200></td>
                  <!--<td><%#= image_tag("#{@post_attachment[0].image}") %></td>-->
                <% end %>
                <td><%= rent_post.location %></td>
                <% if rent_post.price == nil %>
                  <td><%= rent_post.price %></td>
                <% else %>
                  <td><%= rent_post.price %>원</td>
                <% end %>   
              
                <td><%= link_to '', rent_post, :class => "glyphicon glyphicon-eye-open " %></td>
  
                <% if rent_post.user == current_user %>
                  <td><%= link_to '', edit_rent_post_path(rent_post), :class => "glyphicon glyphicon-pencil " %></td>
                  <td><%= link_to '', rent_post, method: :delete, data: { confirm: 'Are you sure?' }, :class => "glyphicon glyphicon-trash " %></td>
                <% else %>
                  <td></td>
                  <td></td>
                <% end %>
                </tr>
              <% end %>
            </tbody>
      </table>
      
    </div>
  </div>
</div>
</p>
<div align="center">
  <%= paginate @rent_posts %>
</div>
<br>

CRS/app/views/rent_posts/new.html.erb
<form style= "font-family: 'Comic Sans MS', cursive, sans-serif; font-size: 300%;" class = "container">
    New Rent Post
</form>

<%= render 'form', rent_post: @rent_post %>

<%= link_to '뒤로가기', rent_posts_path %>

CRS/app/views/rent_posts/show.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

<!------ Include the above in your HEAD tag ---------->

<div class="container">
  <p id="notice"><%= notice %></p>
<hr>




	
<div class="card">
	<div class="row">
		<aside class="col-sm-5 border-right">
<article class="gallery-wrap"> 
<div class="img-big-wrap" align = "CENTER">

<style class="cp-pen-styles">
.thumbnail_img>img{
	width:120px;
	height:80px;
	border: 4px solid #fff;
  border-radius: 4px;
}

.primary {
  width: 400px;
  height: 400px;
  background-size: 350px;
  background-position: center center;
  background-repeat: no-repeat;
  border-radius: 20px;
}
</style>

<div class="primary" style="background-image: url('<%= @post_attachment[0].image %>');"></div>
<div class="thumbnails">
    <% @post_attachment.each do |p| %>
			<% if p.image != nil %>
        <a class="thumbnail_img" data-big="<%= p.image %>"><img src = "<%= p.image %>"></a>
      <% end %>
    <% end %>
</div>

<script src='//production-assets.codepen.io/assets/common/stopExecutionOnTimeout-b2a7b3fe212eaa732349046d8416e00a9dec26eb7fd347590fbced3ab38af52e.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
<script >$('.thumbnail_img').on('click', function() {
  var clicked = $(this);
  var newSelection = clicked.data('big');
  var $img = $('.primary').css("background-image","url(" + newSelection + ")");
  $('.primary').empty().append($img.hide().fadeIn('slow'));
});
//# sourceURL=pen.js
</script>


</div> <!-- slider-product.// -->
</article> <!-- gallery-wrap .end// -->
		</aside>
		
		
		
		
		
		<aside class="col-sm-7">
<article class="card-body p-5">
	<h3 class="title mb-3"><%= @rent_post.lens_name %></h3>

<p class="price-detail-wrap"> 
	<span class="price h3 text-warning"> 
		<span class="currency">Price:</span><span class="num"><%= @rent_post.price %>원</span>
	</span> 
	<span>/<%= @rent_post.location %></span> 
</p> <!-- price-detail-wrap .// -->
<dl class="item-property">
  <dt>Mount:</dt>
  <dd><p><%= @rent_post.mount %> </p></dd>
</dl>
<dl class="param param-feature">
  <dt>Zoom lens:</dt>
  <dd><%= @rent_post.zoom_lens %></dd>
</dl>  <!-- item-property-hor .// -->
<dl class="param param-feature">
  <dt>Distance:</dt>
  <dd><%= @rent_post.distance %>mm</dd>
</dl>  <!-- item-property-hor .// -->
<dl class="param param-feature">
  <dt>Aperture:</dt>
  <dd>F / <%= @rent_post.aperture %></dd>
</dl>  <!-- item-property-hor .// -->
<dl class="param param-feature">
  <dt>Is:</dt>
  <dd><%= @rent_post.is %></dd>
</dl>  <!-- item-property-hor .// -->

<hr>
	<div class="row">
		<div class="col-sm-5">
			<dl class="param param-inline">
			  <dd>
			  	<dl class="param param-feature">
          <dt>Rented:</dt>
          <dd><%= @rent_post.rented %></dd>
        </dl>  <!-- item-property-hor .// -->
			  </dd>
			</dl>  <!-- item-property .// -->
		</div> <!-- col.// -->
		<div class="col-sm-7">
			<dl class="param param-inline">
				  <dl class="param param-feature">
            <dt>Content:</dt>
            <dd><%= @rent_post.content %></dd>
          </dl>  <!-- item-property-hor .// -->
			</dl>  <!-- item-property .// -->
		</div> <!-- col.// -->
	</div> <!-- row.// -->
	<hr>
	<% if can? :update, @rent_post %>
  <%= link_to 'Edit', edit_rent_post_path(@rent_post) %> |
  <% end %>
  
  <%= link_to 'Back', rent_posts_path %>
  
  <!--댓글 Rent_Comments-->
  <hr>
  
  <form action = '/rent_comments' method = 'POST'>
  	<input type = 'hidden' name = 'authenticity_token' value = <%= @token %>></input>
  	<input type = 'hidden' name = 'rent_post_id' value = <%= @rent_post.id %>></input>
  	<input type = 'hidden' name = 'current_user' value = <%= @current_user.id%>></input>
  	
  	<strong>댓글 : </strong>
  	<input type = 'text', name='input_content'></input>
  	<input type = 'submit'></input>
  </form>
  
  <!-- 댓글 출력부분 -->
  <% @rent_post.rent_comments.each do |comment| %>
		<p>
			<%= comment.user.email %>
			<% if comment.user_id == @rent_post.user_id %>
				(작성자)
			<% end %>
			: <%= comment.content %>
				<% if comment.user_id == @current_user.id%>
					<a href='/rent_comments/<%= comment.id %>'
				  	 data-confirm='댓글을 삭제합니다.'
				  	 data-method='DELETE'>
					 | 삭제</a>
				<% end %>
		</p>  
	<% end %>


</article> <!-- card-body.// -->
		</aside> <!-- col.// -->
	</div> <!-- row.// -->
</div> <!-- card.// -->


</div>
<!--container.//-->